### PR TITLE
Fixed Mission File

### PR DESCRIPTION
**Pull request by DGCHoot**
Removed the missing .paa's from stuff, Will now boot normally.

### CODE REVIEW

**Comment by TMschar** [comment]
Hi Hootsir,

Thank you for submitting a pull request.

I have a question, did you have any DLCs enabled when you changed this? I guess you changed it in the mission editor (3DEN)?

**Comment by DGCHoot** [comment]
All I did was removal of .paas nothing else was added, it was a simple fix,
it was done via 3DEN,
More or less i was making it public friendly, as vehicles aren't required to have their skins.. but unfortunately for the Mission to load it must have the custom textures in it, or else you must remove the .paa's from the billboard and the vendors.

**Comment by TMschar** [comment]
Alright,

I just remembered as well that the objects now are available to everyone (DLC content) so what I brought up isn't an issue regardless.

Merging your PR...

Thanks again!

**Comment by DGCHoot** [comment]
I got you bud no worries

**Pull request merged**
